"""
Файл используется в сборке по поиску мертвого кода
http://ci-platform.sbis.ru/job/MAINTENANCE/job/check%20dead%20code/
Здесь указаны атрибуты для исключения.
"""

any_crumbs_vcbc  # unused variable (int/pages/vdom/vdom_breadcrumbs.py:7)
one_crumb_vcbc  # unused variable (int/pages/vdom/vdom_breadcrumbs.py:8)
two_crumbs_vcbc  # unused variable (int/pages/vdom/vdom_breadcrumbs.py:9)
two_diff_crumbs_vcbc  # unused variable (int/pages/vdom/vdom_breadcrumbs.py:10)
opener_sticky_btn  # unused variable (int/pages/vdom/vdom_containers.py:167)
opener_dimension_btn  # unused variable (int/pages/vdom/vdom_containers.py:168)
opener_target_btn  # unused variable (int/pages/vdom/vdom_containers.py:170)
opener_enabled_vccb  # unused variable (int/pages/vdom/vdom_containers.py:175)
opener_canmaximize_vccb  # unused variable (int/pages/vdom/vdom_containers.py:177)
opener_maximized_vccb  # unused variable (int/pages/vdom/vdom_containers.py:178)
opener_modal_vccb  # unused variable (int/pages/vdom/vdom_containers.py:179)
opener_setside_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:188)
opener_setdirection_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:189)
opener_sethorizontal_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:190)
opener_setvertical_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:191)
opener_setverticalalign_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:192)
opener_setoffsetx_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:193)
opener_setoffsety_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:194)
search_1_vcstb  # unused variable (int/pages/vdom/vdom_filter.py:20)
search_2_vcstb  # unused variable (int/pages/vdom/vdom_filter.py:21)
search_4_vcstb  # unused variable (int/pages/vdom/vdom_filter.py:22)
fast_filter_2_vcff  # unused variable (int/pages/vdom/vdom_filter.py:24)
fast_filter_3_vcff  # unused variable (int/pages/vdom/vdom_filter.py:25)
fast_filter_4_vcff  # unused variable (int/pages/vdom/vdom_filter.py:26)
filter_btn_2_vcfb  # unused variable (int/pages/vdom/vdom_filter.py:28)
filter_btn_3_vcfb  # unused variable (int/pages/vdom/vdom_filter.py:29)
filter_btn_4_vcfb  # unused variable (int/pages/vdom/vdom_filter.py:30)
main_area_elm  # unused variable (int/pages/vdom/vdom_input.py:63)
main_number_elm  # unused variable (int/pages/vdom/vdom_input.py:69)
main_psw_inp  # unused variable (int/pages/vdom/vdom_input.py:71)
main_psw_elm  # unused variable (int/pages/vdom/vdom_input.py:72)
suggest_vcstb  # unused variable (int/pages/vdom/vdom_input.py:175)
suggest_nofooter_vcstb  # unused variable (int/pages/vdom/vdom_input.py:177)
single_vcfl  # unused variable (int/pages/vdom/vdom_input.py:187)
bold_vcfl  # unused variable (int/pages/vdom/vdom_input.py:188)
accent_vcfl  # unused variable (int/pages/vdom/vdom_input.py:189)
primary_vcfl  # unused variable (int/pages/vdom/vdom_input.py:190)
switch_vcs  # unused variable (int/pages/vdom/vdom_toggle.py:36)
simple_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:130)
subparagraphs_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:132)
comments_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:133)
no_icons_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:134)
add_text_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:135)
icon_header_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:136)
icon_button_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:137)
groups_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:140)
old_float_btn  # int/pages/vdom/vdom_containers.py:170: unused variable
old_dialog_btn  # int/pages/vdom/vdom_containers.py:171: unused variable
old_sticky_btn  # int/pages/vdom/vdom_containers.py:172: unused variable
