"""
Файл используется в сборке по поиску мертвого кода
http://ci-platform.sbis.ru/job/MAINTENANCE/job/check%20dead%20code/
Здесь указаны атрибуты для исключения.
"""

any_crumbs_vcbc  # unused variable (int/pages/vdom/vdom_breadcrumbs.py:7)
one_crumb_vcbc  # unused variable (int/pages/vdom/vdom_breadcrumbs.py:8)
two_crumbs_vcbc  # unused variable (int/pages/vdom/vdom_breadcrumbs.py:9)
two_diff_crumbs_vcbc  # unused variable (int/pages/vdom/vdom_breadcrumbs.py:10)
old_float_btn  # unused variable (int/pages/vdom/vdom_containers.py:180)
old_dialog_btn  # unused variable (int/pages/vdom/vdom_containers.py:181)
old_sticky_btn  # unused variable (int/pages/vdom/vdom_containers.py:182)
opener_sticky_btn  # unused variable (int/pages/vdom/vdom_containers.py:199)
opener_dimension_btn  # unused variable (int/pages/vdom/vdom_containers.py:200)
opener_target_btn  # unused variable (int/pages/vdom/vdom_containers.py:202)
opener_enabled_vccb  # unused variable (int/pages/vdom/vdom_containers.py:207)
opener_canmaximize_vccb  # unused variable (int/pages/vdom/vdom_containers.py:209)
opener_maximized_vccb  # unused variable (int/pages/vdom/vdom_containers.py:210)
opener_modal_vccb  # unused variable (int/pages/vdom/vdom_containers.py:211)
opener_setside_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:220)
opener_setdirection_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:221)
opener_sethorizontal_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:222)
opener_setvertical_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:223)
opener_setverticalalign_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:224)
opener_setoffsetx_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:225)
opener_setoffsety_vccbx  # unused variable (int/pages/vdom/vdom_containers.py:226)
search_1_vcstb  # unused variable (int/pages/vdom/vdom_filter.py:31)
search_2_vcstb  # unused variable (int/pages/vdom/vdom_filter.py:32)
search_4_vcstb  # unused variable (int/pages/vdom/vdom_filter.py:33)
fast_filter_2_vcff  # unused variable (int/pages/vdom/vdom_filter.py:35)
fast_filter_3_vcff  # unused variable (int/pages/vdom/vdom_filter.py:36)
fast_filter_4_vcff  # unused variable (int/pages/vdom/vdom_filter.py:37)
filter_btn_2_vcfb  # unused variable (int/pages/vdom/vdom_filter.py:39)
filter_btn_3_vcfb  # unused variable (int/pages/vdom/vdom_filter.py:40)
filter_btn_4_vcfb  # unused variable (int/pages/vdom/vdom_filter.py:41)
main_area_elm  # unused variable (int/pages/vdom/vdom_input.py:87)
main_number_elm  # unused variable (int/pages/vdom/vdom_input.py:93)
main_psw_inp  # unused variable (int/pages/vdom/vdom_input.py:95)
main_psw_elm  # unused variable (int/pages/vdom/vdom_input.py:96)
suggest_vcstb  # unused variable (int/pages/vdom/vdom_input.py:208)
suggest_nofooter_vcstb  # unused variable (int/pages/vdom/vdom_input.py:210)
single_vcfl  # unused variable (int/pages/vdom/vdom_input.py:223)
bold_vcfl  # unused variable (int/pages/vdom/vdom_input.py:224)
accent_vcfl  # unused variable (int/pages/vdom/vdom_input.py:225)
primary_vcfl  # unused variable (int/pages/vdom/vdom_input.py:226)
inn_1_inp  # unused variable (int/pages/vdom/vdom_input.py:241)
inn_2_inp  # unused variable (int/pages/vdom/vdom_input.py:244)
inn_2_elm  # unused variable (int/pages/vdom/vdom_input.py:245)
switch_vcs  # unused variable (int/pages/vdom/vdom_toggle.py:48)
simple_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:131)
subparagraphs_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:133)
comments_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:134)
no_icons_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:135)
add_text_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:136)
icon_header_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:137)
icon_button_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:138)
groups_btn  # unused variable (reg/pages/vdom/vdom_toggle.py:141)
