define([
'../../components/Data/Adapter/resources/test/Json.test',
'../../components/Data/Adapter/resources/test/Sbis.test',
'../../components/Data/Collection/resources/test/ArrayEnumerator.test',
'../../components/Data/Collection/resources/test/List.test',
'../../components/Data/resources/test/Di.test',
'../../components/Data/resources/test/Factory.test',
'../../components/Data/resources/test/Model.test',
'../../components/Data/resources/test/Serializer.test',
'../../components/Data/Source/resources/test/DataSet.test',
'../../components/Data/Source/resources/test/Memory.test',
'../../components/Data/Source/resources/test/SbisService.test',
'../../components/__DataSet/DataFactory/resources/DataFactory.test',
'../../components/__DataSet/DataSet/resources/test/DataSet.test',
'../../components/__DataSet/DataSet/resources/test/Record.test',
'../../components/__DataSet/DataSource/resources/test/SbisServiceSource.test',
'../../components/__DataSet/DataSource/resources/test/StaticSource.test'
]);